**Future Skill**



1.   Data
2.   Software
3. Design



#Contents



- review class OOP
- try except
- assert
- review loop + dictionary
- csv, API, json, context manager
- list comprehension
- web scraping
- numpy pandas sqlite sklearn



##super class

In [20]:
#super class
class Person:
    def __init__(self, name):
        self.name = name
    def hey(self):
        print("hello world")
    def sayhi(self):
        print(f"Hi my name is {self.name}!")

class Employee(Person): #superclass คือต่อยอดจากclass person อีกที #มี attribute เป็นclass
    def __init__(self, name, company):
        super().__init__(name) #ใส่ attribute เก่าเข้าไปก่อน
        self.company = company
    def potato(self):
        print("potato is very good!")
    def sayhi(self):
        print( f"Hi my name is {self.name} and I work at {self.company}.")

In [21]:
toy= Person("Toy")
john = Employee("john", "Google")
toy.sayhi()
john.sayhi()

Hi my name is Toy!
Hi my name is john and I work at Google.


In [22]:
toy.hey()

hello world


In [23]:
john.hey()

hello world


In [24]:
john.potato()

potato is very good!


##try except

In [26]:
#try-except block
#1/0 error
try:
    1/0
except:
    print("this is an error message") #จะprint when error

this is an error message


In [29]:
try:
    1/1 #not error ผลคือไม่มีไรเกิดขึ้น
except:
    print("this is an error message")

In [30]:
try:
    print(x)
except:
    print("this is an error message")

this is an error message


In [31]:
x=10
try:
    print(x)
except:
    print("this is an error message")

10


In [40]:
try:
    #1/0
    #print(y)
    x = "hello"
    #x= int(x)
except ZeroDivisionError:
    print("Cannot divide a number with zero")
except NameError: #เลือกประเภท error
    print("Variable is not found.")
except ValueError:
    print("please check your data type again")
else:
    print("Done!")
finally: #ยังไงก็รัน
    print("last line")

Done!
last line


##assert

In [41]:
#assert
#ถ้าหลัง assert เป็น True จะไม่ error
assert 1+1==2

In [43]:
assert 1+1==5, "1+1 must be 2"

AssertionError: ignored

In [46]:
def check_this(a,b):
    assert a+b>10, "a+b should be more than 10"
    return a+b

In [47]:
check_this(1,2)

AssertionError: ignored

In [48]:
check_this(10,20)

30

In [49]:
def check_this(a: int,b: int) -> int:
    assert a+b>10, "a+b should be more than 10"
    return a+b

In [50]:
check_this(10,20)

30

##lambda function

In [52]:
#เขียน function จบใน 1 1บรรทัด
def greeting(name):
    print("hello " + name)

In [56]:
greeting_new = lambda name: print("hello " + name)

In [58]:
greeting_new("toy")

hello toy


In [59]:
def odd_or_even(num):
    if num % 2 == 0:
        print("Even")
    else:
        print("Odd")

In [60]:
#lambda เหมาะกับ simple function
odd_or_even_new = lambda num: "even" if num % 2 == 0 else "odd"

In [61]:
odd_or_even_new(4)

'even'

In [62]:
odd_or_even_new(5)

'odd'

##Dictionary

In [66]:
#list of colored ball
balls=["red", "red", "green", "blue", "blue"]

In [72]:
x={}
x['key1']=5
x["key2"]="r"
print(x)

{'key1': 5, 'key2': 'r'}


In [69]:
result={}
for ball in balls:
    if ball in result:
        result[ball] += 1 #ถ้าเจอเพิ่ม+1
    else:
        result[ball] = 1 #ถ้ายังไม่มีนับ1
print(result)

{'red': 2, 'green': 1, 'blue': 2}


In [73]:
def summary(list_items) :
    result={}
    for item in list_items:
        if item in result:
            result[item] += 1 #ถ้าเจอเพิ่ม+1
        else:
            result[item] = 1 #ถ้ายังไม่มีนับ1
    print(result)

In [74]:
summary(balls)

{'red': 2, 'green': 1, 'blue': 2}


##CSV file

In [75]:
#CSV= comma separated value

In [78]:
#run as bash
!pwd
!ls
!ls sample_data/

/content
hotel.csv  sample_data
anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [79]:
!mkdir newFolder

In [80]:
!rmdir newFolder

In [81]:
!cat hotel.csv

id,hotel,location,price
1,Accor,Thailand,50
2,Ibis,Italy,60
3,London,UK,35
4,Seoul,Koea,30
5,Le Concord,USA,25


In [83]:
import csv

file = open("hotel.csv")

data = csv.reader(file)

for row in data:
    print(row)

file.close()

['\ufeffid', 'hotel', 'location', 'price']
['1', 'Accor', 'Thailand', '50']
['2', 'Ibis', 'Italy', '60']
['3', 'London', 'UK', '35']
['4', 'Seoul', 'Koea', '30']
['5', 'Le Concord', 'USA', '25']


In [84]:
import csv

try:
    file = open("hotel.csv")
    data = csv.reader(file)
    file.close()
except FileNotFoundError:
    print("File not found.")
else:
    print("Load data successfully")


Load data successfully


In [87]:
#context manager
import csv

try:
    with open("hotel.csv", "r") as file: #withจะปิดfileให้เลย
        data = csv.reader(file)
        for row in data:
            print(row)
except:
    print("Found some error")

['\ufeffid', 'hotel', 'location', 'price']
['1', 'Accor', 'Thailand', '50']
['2', 'Ibis', 'Italy', '60']
['3', 'London', 'UK', '35']
['4', 'Seoul', 'Koea', '30']
['5', 'Le Concord', 'USA', '25']


In [89]:
#context manger
csv_data = [] #empty list

with open("hotel.csv", "r") as file: #withจะปิดfileให้เลย
    data = csv.reader(file)
    for row in data:
        csv_data.append(row)

print(csv_data)

[['\ufeffid', 'hotel', 'location', 'price'], ['1', 'Accor', 'Thailand', '50'], ['2', 'Ibis', 'Italy', '60'], ['3', 'London', 'UK', '35'], ['4', 'Seoul', 'Koea', '30'], ['5', 'Le Concord', 'USA', '25']]


In [92]:
#modern python
import pandas as pd

df = pd.read_csv("hotel.csv")
df

id       hotel  location  price
0   1       Accor  Thailand     50
1   2        Ibis     Italy     60
2   3      London        UK     35
3   4       Seoul      Koea     30
4   5  Le Concord       USA     25

In [94]:
#create new column
df["price_double"] = df["price"]*2

df

id       hotel  location  price  price_double
0   1       Accor  Thailand     50           100
1   2        Ibis     Italy     60           120
2   3      London        UK     35            70
3   4       Seoul      Koea     30            60
4   5  Le Concord       USA     25            50

In [95]:
#save file csv
df.to_csv("hotel_modified.csv")

In [96]:
!cat hotel_modified.csv

,id,hotel,location,price,price_double
0,1,Accor,Thailand,50,100
1,2,Ibis,Italy,60,120
2,3,London,UK,35,70
3,4,Seoul,Koea,30,60
4,5,Le Concord,USA,25,50


In [ ]:
#สรุปmodern python
#อ่าน
import pandas as pd
df = pd.read_csv("hotel.csv")
#update
df["price_double"] = df["price"]*2
#write file
df.to_csv("hotel_modified.csv")

In [99]:
#write csv file
#"w" write mode
import csv

headers = ["id", "name", "age"]
data = [
    [1, "toy", 25],
    [2, "jisoo", 26],
    [3, "john", 32]
]

with open("newfile.csv","w") as file:
    writer = csv.writer(file)
    writer.writerow(headers)
    writer.writerows(data)

In [100]:
!cat newfile.csv

id,name,age
1,toy,25
2,jisoo,26
3,john,32


In [105]:
result = []
with open("newfile.csv", "r") as file:
    data = csv.reader(file)
    for row in data:
        result.append(row)
print(result)

[['id', 'name', 'age'], ['1', 'toy', '25'], ['2', 'jisoo', '26'], ['3', 'john', '32']]


##Regular Expression

In [117]:
import re

text = "a duck walk into a bar duck"

re.search("duck", text) #span=(2,6) แปลว่าตัวอักษรที่2-5

<re.Match object; span=(2, 6), match='duck'>

In [118]:
from re import search

text = "a duck walk into a bar duck"

search("duck", text)

<re.Match object; span=(2, 6), match='duck'>

In [119]:
#retuen ค่าเป็น True,False
import re
text = "a duck walk into a bar duck"
result = re.search("duck", text)

if result:
    print("Duck found")
else:
    print('Duck not found')

Duck found


##List Comprehension
เขียนจบใน 1 บรรทัด

In [121]:
numbers = [1, 2, 3, 4, 5]

result = [num*2 for num in numbers]
print(result)

[2, 4, 6, 8, 10]


In [122]:
odd_nums = [num for num in numbers if num%2 == 1]
even_nums = [num for num in numbers if num%2 == 0]

print(odd_nums, even_nums)

[1, 3, 5] [2, 4]


##JSON => JavaScript Object Notation
หน้าตาเหมือน dictionary <br>
ใช้ ".." เท่านั้น '..' ไม่ได้

In [123]:
!ls *.json

toy.json


In [124]:
import json

with open("toy.json", "r") as file:
    data = json.load(file)

In [125]:
data

{'name': 'toy',
 'age': 34,
 'movie_lover': True,
 'movies': ['batman', 'superman']}

In [130]:
data["movies"][1]

'superman'

In [131]:
# create new .json file
school = {
    "name": "bootcamp",
    "batch": 7,
    "duration": "4 months"
}

with open("newjsonfile.json", "w") as file:
    json.dump(school, file)

In [132]:
!cat newjsonfile.json

{"name": "bootcamp", "batch": 7, "duration": "4 months"}

In [133]:
with open("newjsonfile.json", "r") as file:
    data2 = json.load(file)

data2

{'name': 'bootcamp', 'batch': 7, 'duration': '4 months'}

##API
https://swapi.dev/

In [143]:
import requests

url = "https://swapi.dev/api/people/9"

result = requests.get(url)
data_json = result.json()
data_json

{'name': 'Biggs Darklighter',
 'height': '183',
 'mass': '84',
 'hair_color': 'black',
 'skin_color': 'light',
 'eye_color': 'brown',
 'birth_year': '24BBY',
 'gender': 'male',
 'homeworld': 'https://swapi.dev/api/planets/1/',
 'films': ['https://swapi.dev/api/films/1/'],
 'species': [],
 'vehicles': [],
 'starships': ['https://swapi.dev/api/starships/12/'],
 'created': '2014-12-10T15:59:50.509000Z',
 'edited': '2014-12-20T21:17:50.323000Z',
 'url': 'https://swapi.dev/api/people/9/'}

In [142]:
data_json["name"]

'Biggs Darklighter'

In [148]:
list(range(1, 11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [155]:
#request API people1-10
from requests import get
from time import sleep

nums = list(range(1,6))
result = []

for i in nums:
    url = f"https://swapi.dev/api/people/{i}" #1-n
    response = get(url)
    data = response.json()
    row = [
        data["name"],
        data["height"],
        data["mass"],
        data["gender"]
    ]
    result.append(row)
    sleep(1) #second #เว้นช่วงลูปละ1วิ ป้องกัน api ล่ม



In [156]:
import pandas as pd

df = pd.DataFrame(result, columns=["name", "height", "mass", "gender"])
df

name height mass  gender
0  Luke Skywalker    172   77    male
1           C-3PO    167   75     n/a
2           R2-D2     96   32     n/a
3     Darth Vader    202  136    male
4     Leia Organa    150   49  female

##HW01 - find public API

##Web Scraping
https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc

In [158]:
!pip install gazpacho

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for gazpacho: filename=gazpacho-1.1-py3-none-any.whl size=7461 sha256=ebf6626c221e79cbefbaa62e535bd8e8b4321fa339f8c37c77f8506f351d76fd
  Stored in directory: /root/.cache/pip/wheels/9b/bf/9f/8c8849499462415fa5cdf0d9edb1103c189bdbece90c51488e
Successfully built gazpacho


In [160]:
!pip list | grep "gaz"

gazpacho                         1.1


In [162]:
from gazpacho import Soup
from requests import get

url ="https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"

response = get(url)
#print(response.status_code)
imdb = Soup(response.text)

In [ ]:
#case ได้เป็นภาษาอื่นๆ
#url ="https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"
#้้headers = {"Accept-Language": "en-US"}
#response = get(url, headers=headers)
#imdb = Soup(response.text)

In [164]:
type(imdb)

gazpacho.soup.Soup

In [168]:
imdb.find("title")

[<title>IMDb &quot;Top 100&quot;
 (Sorted by IMDb Rating Descending) - IMDb</title>,
 <title>IMDb, an Amazon company</title>]

In [167]:
imdb.find("title")[0].strip()

'IMDb "Top 100" (Sorted by IMDb Rating Descending) - IMDb'

In [177]:
title_list = imdb.find("h3", {"class":"lister-item-header"}) #class="lister-item-header"

In [180]:
titles = [title.strip() for title in title_list]

print(titles)

['1. The Shawshank Redemption (1994)', '2. The Godfather (1972)', '3. The Dark Knight (2008)', "4. Schindler's List (1993)", '5. The Godfather Part II (1974)', '6. The Lord of the Rings: The Return of the King (2003)', '7. 12 Angry Men (1957)', '8. Pulp Fiction (1994)', '9. Spider-Man: Across the Spider-Verse (2023)', '10. Inception (2010)', '11. The Lord of the Rings: The Fellowship of the Ring (2001)', '12. Fight Club (1999)', '13. Forrest Gump (1994)', '14. The Good, the Bad and the Ugly (1966)', '15. The Lord of the Rings: The Two Towers (2002)', '16. Interstellar (2014)', '17. Goodfellas (1990)', '18. The Matrix (1999)', "19. One Flew Over the Cuckoo's Nest (1975)", '20. Star Wars: Episode V - The Empire Strikes Back (1980)', '21. Oppenheimer (2023)', '22. Se7en (1995)', '23. The Silence of the Lambs (1991)', '24. The Green Mile (1999)', '25. Saving Private Ryan (1998)', '26. Terminator 2: Judgment Day (1991)', '27. Star Wars: Episode IV - A New Hope (1977)', '28. Spirited Away (2

In [183]:
runtimes = imdb.find("span",{"class": "runtime"})
runtimes = [time.strip() for time in runtimes]
print(runtimes)

['142 min', '175 min', '152 min', '195 min', '202 min', '201 min', '96 min', '154 min', '140 min', '148 min', '178 min', '139 min', '142 min', '178 min', '179 min', '169 min', '145 min', '136 min', '133 min', '124 min', '180 min', '127 min', '118 min', '189 min', '169 min', '137 min', '121 min', '125 min', '130 min', '116 min', '130 min', '207 min', '133 min', '155 min', '130 min', '151 min', '116 min', '165 min', '132 min', '117 min', '106 min', '110 min', '106 min', '150 min', '88 min', '119 min', '109 min', '112 min', '102 min', '89 min']


In [187]:
import pandas as pd

df = pd.DataFrame({
    "title": titles,
    "runtime": runtimes
})

df.head()

title  runtime
0  1. The Shawshank Redemption (1994)  142 min
1             2. The Godfather (1972)  175 min
2           3. The Dark Knight (2008)  152 min
3          4. Schindler's List (1993)  195 min
4     5. The Godfather Part II (1974)  202 min

In [188]:
df.to_csv("imdb_data.csv")

##BASIC DATA TOOLS


*   numpy
*   pandas
* sklearn



NUMPY => numerical python
* array = ([...])

In [193]:
import numpy as np
x = [1,2,3,4,5]
x*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [196]:
num_arr = np.array(x)
num_arr*2

array([ 2,  4,  6,  8, 10])

Statistic

In [203]:
np.sum(num_arr)
np.mean(num_arr)
np.std(num_arr)
np.min(num_arr)
np.max(num_arr)
len(num_arr)
np.median(num_arr)

3.0

In [202]:
num_arr.mean()

3.0

MATRIX (2D array) <br>
array([[..]])

In [204]:
m1 = np.array([
    [1,2],
    [3,4]
])

In [205]:
m1+2

array([[3, 4],
       [5, 6]])

In [206]:
m1*2

array([[2, 4],
       [6, 8]])

In [207]:
m1

array([[1, 2],
       [3, 4]])

In [212]:
m2= np.array([
    [5,5],
    [4,2]
])

print(m1 ,"\n"*2, m2)

[[1 2]
 [3 4]] 

 [[5 5]
 [4 2]]


In [214]:
m1+m2

array([[6, 7],
       [7, 6]])

In [216]:
m1*m2 #ไม่เหมือนคูณแมททริก

array([[ 5, 10],
       [12,  8]])

In [218]:
m1.dot(m2) #คูณแมททริก
#np.dot(m1,m2)

array([[13,  9],
       [31, 23]])

##PANDAS

In [220]:
import pandas as pd
import numpy as np

In [221]:
hotel = pd.read_csv("hotel.csv")

In [222]:
hotel.shape #(row, col)

(5, 4)

In [223]:
hotel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        5 non-null      int64 
 1   hotel     5 non-null      object
 2   location  5 non-null      object
 3   price     5 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes


In [224]:
hotel.describe()

id     price
count  5.000000   5.00000
mean   3.000000  40.00000
std    1.581139  14.57738
min    1.000000  25.00000
25%    2.000000  30.00000
50%    3.000000  35.00000
75%    4.000000  50.00000
max    5.000000  60.00000

In [225]:
hotel.describe(include="all")

id  hotel  location     price
count   5.000000      5         5   5.00000
unique       NaN      5         5       NaN
top          NaN  Accor  Thailand       NaN
freq         NaN      1         1       NaN
mean    3.000000    NaN       NaN  40.00000
std     1.581139    NaN       NaN  14.57738
min     1.000000    NaN       NaN  25.00000
25%     2.000000    NaN       NaN  30.00000
50%     3.000000    NaN       NaN  35.00000
75%     4.000000    NaN       NaN  50.00000
max     5.000000    NaN       NaN  60.00000

In [227]:
#hotel["hotel"]
hotel.hotel

0         Accor
1          Ibis
2        London
3         Seoul
4    Le Concord
Name: hotel, dtype: object

In [229]:
hotel["vat"] = hotel["price"]*0.07

hotel

id       hotel  location  price   vat
0   1       Accor  Thailand     50  3.50
1   2        Ibis     Italy     60  4.20
2   3      London        UK     35  2.45
3   4       Seoul      Koea     30  2.10
4   5  Le Concord       USA     25  1.75

In [231]:
#query for filter row
hotel.query("price <= 40")


id       hotel location  price   vat
2   3      London       UK     35  2.45
3   4       Seoul     Koea     30  2.10
4   5  Le Concord      USA     25  1.75

In [232]:
value_hotel = hotel.query("price <= 40")
value_hotel.to_csv("value_hotel.csv")

In [235]:
#ลบ col
hotel.drop("vat", axis=1)

id       hotel  location  price
0   1       Accor  Thailand     50
1   2        Ibis     Italy     60
2   3      London        UK     35
3   4       Seoul      Koea     30
4   5  Le Concord       USA     25

In [236]:
hotel0=hotel
hotel.drop(["id", "vat"], axis=1) #inplace=true คือแทนไปเลย

hotel  location  price
0       Accor  Thailand     50
1        Ibis     Italy     60
2      London        UK     35
3       Seoul      Koea     30
4  Le Concord       USA     25

In [237]:
hotel

id       hotel  location  price   vat
0   1       Accor  Thailand     50  3.50
1   2        Ibis     Italy     60  4.20
2   3      London        UK     35  2.45
3   4       Seoul      Koea     30  2.10
4   5  Le Concord       USA     25  1.75

In [239]:
hotel.drop(["id", "vat"], axis=1)
hotel

id       hotel  location  price   vat
0   1       Accor  Thailand     50  3.50
1   2        Ibis     Italy     60  4.20
2   3      London        UK     35  2.45
3   4       Seoul      Koea     30  2.10
4   5  Le Concord       USA     25  1.75

In [243]:
hotel.query("price <= 40 or location == 'Italy'")

id       hotel location  price   vat
1   2        Ibis    Italy     60  4.20
2   3      London       UK     35  2.45
3   4       Seoul     Koea     30  2.10
4   5  Le Concord      USA     25  1.75

In [244]:
hotel.query("price <= 40 and location == 'UK'")

id   hotel location  price   vat
2   3  London       UK     35  2.45

SKLEARN for ML

In [245]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pandas as pd

In [246]:
mtcars = pd.read_csv("https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv")

In [247]:
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

Linear Regression

In [260]:
#prepare
X= mtcars[["hp", "wt", "am"]]
y=mtcars["mpg"]

#split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) #set.seed(42)

#train model
model = LinearRegression()
model.fit(X_train, y_train)

#test model
pred = model.predict(X_test)

#evaluate
import sklearn.metrics as metrics
from math import sqrt
#MAE
MAE = metrics.mean_absolute_error(y_test, pred)
#MSE
MSE = metrics.mean_squared_error(y_test, pred)
#RMSE
RMSE = sqrt(metrics.mean_squared_error(y_test, pred))
#R squre
R = metrics.r2_score(y_test, pred)
print(MAE, MSE, RMSE, R)

2.0710117400488417 7.319771016726086 2.7055075340360975 0.8169328713367676


In [257]:
import sklearn.metrics
sklearn.metrics.mean_absolute_error(y_test, pred)

2.0710117400488417

Decision Tree

In [261]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
import pandas as pd

#prepare
X= mtcars[["hp", "wt", "am"]]
y=mtcars["mpg"]

#split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) #set.seed(42)

#train model
model = DecisionTreeRegressor()
model.fit(X_train, y_train)

#test model
pred = model.predict(X_test)

#evaluate
import sklearn.metrics as metrics
from math import sqrt
#MAE
MAE = metrics.mean_absolute_error(y_test, pred)
#MSE
MSE = metrics.mean_squared_error(y_test, pred)
#RMSE
RMSE = sqrt(metrics.mean_squared_error(y_test, pred))
#R squre
R = metrics.r2_score(y_test, pred)
print(MAE, MSE, RMSE, R)

2.4714285714285706 9.609999999999994 3.099999999999999 0.759654352242219


Random Forest

In [264]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import pandas as pd

#prepare
X= mtcars[["hp", "wt", "am"]]
y=mtcars["mpg"]

#split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) #set.seed(42)

#train model
model = RandomForestRegressor()
model.fit(X_train, y_train)

#test model
pred = model.predict(X_test)

#evaluate
import sklearn.metrics as metrics
from math import sqrt
#MAE
MAE = metrics.mean_absolute_error(y_test, pred)
#MSE
MSE = metrics.mean_squared_error(y_test, pred)
#RMSE
RMSE = sqrt(metrics.mean_squared_error(y_test, pred))
#R squre
R = metrics.r2_score(y_test, pred)
print(f"MAE = {MAE}, MSE = {MSE}, RMSE = {RMSE}, R square = {R}")

MAE = 2.1362857142857066, MSE = 8.634209428571385, RMSE = 2.938402530044409, R square = 0.784058828513389


In [263]:
#classifi case
#from sklearn.metrics import classification_report, confusion_matrix
#print(classification_report(y_test, pred))
#print(confusion_matrix(y_test,y_predict))

ValueError: ignored